version: '3.8'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
       - ./pg01.sql:/docker-entrypoint-initdb.d/pg01.sql
       - data:/var/lib/postgresql/data
    networks:
      - net

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - net
        
networks:
  net:

volumes:
  data: